[package]
name = "chip8-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beep = "0.3.0"
clap = { version = "4.4.6", features = ["derive"] }
rand = "0.8.5"
raylib = "5.0.1"
